<!-- JSON-LD markup generated by Google Structured Data Markup Helper. -->
<script type="application/ld+json">
[
  {
    "@context": "http://schema.org",
    "@type": "Product",
    "name": "DIGI 55 Inches Smart – 4K UHD, WebOS, Dolby Audio, Frameless, B.",
    "image": "https://digiappliances.com/img/products/tvs/55/tv-01.png",
    "url": "https://digiappliances.com/products/smart-tv-55-inch-uhd",
    "brand": {
      "@type": "Brand",
      "logo": "https://digiappliances.com/img/digi-logo.svg"
    }
  },
  {
    "@context": "http://schema.org",
    "@type": "Product",
    "name": "DIGI 43 Inches Smart – FHD Smart TV, Android OS, Wi-Fi, Framele...",
    "image": "https://digiappliances.com/img/products/tvs/43-smart/tv-02.png",
    "url": "https://digiappliances.com/products/smart-tv-43-inch-smart",
    "brand": {
      "@type": "Brand",
      "logo": "https://digiappliances.com/img/digi-logo.svg"
    }
  },
  {
    "@context": "http://schema.org",
    "@type": "Product",
    "name": "DIGI 43 Inches – FHD LED, Frameless Design, Dynamic Contrast, B...",
    "image": "https://digiappliances.com/img/products/tvs/43-led/tv-04.png",
    "url": "https://digiappliances.com/products/tv-43-inch-led",
    "brand": {
      "@type": "Brand",
      "logo": "https://digiappliances.com/img/digi-logo.svg"
    }
  },
  {
    "@context": "http://schema.org",
    "@type": "Product",
    "name": "DIGI 32 inches – HD LED, Frameless Design, AC/DC, Built-in Rece...",
    "image": "https://digiappliances.com/img/products/tvs/32/tv-03.png",
    "url": "https://digiappliances.com/products/tv-32-inch-led",
    "brand": {
      "@type": "Brand",
      "logo": "https://digiappliances.com/img/digi-logo.svg"
    }
  },
  {
    "@context": "http://schema.org",
    "@type": "Product",
    "name": "DIGI Washing Machine 8kg – Twin Tub, High-Efficiency Motor, Dur...",
    "image": "https://digiappliances.com/img/products/washing-machine/wm-8.png",
    "url": "https://digiappliances.com/products/washing-machine-8kg",
    "brand": {
      "@type": "Brand",
      "logo": "https://digiappliances.com/img/digi-logo.svg"
    }
  },
  {
    "@context": "http://schema.org",
    "@type": "Product",
    "name": "DIGI Washing Machine 10kg – Twin Tub, High-Efficiency Motor, Du...",
    "image": "https://digiappliances.com/img/products/washing-machine/wm-10.png",
    "url": "https://digiappliances.com/products/washing-machine-10kg",
    "brand": {
      "@type": "Brand",
      "logo": "https://digiappliances.com/img/digi-logo.svg"
    }
  },
  {
    "@context": "http://schema.org",
    "@type": "Product",
    "name": "DIGI Washing Machine 12kg – Twin Tub, High-Efficiency Motor, Du...",
    "image": "https://digiappliances.com/img/products/washing-machine/wm-12.png",
    "url": "https://digiappliances.com/products/washing-machine-12kg",
    "brand": {
      "@type": "Brand",
      "logo": "https://digiappliances.com/img/digi-logo.svg"
    }
  },
  {
    "@context": "http://schema.org",
    "@type": "Product",
    "name": "DIGI 126 Liters Refrigerator – Fast Cooling, Tempered Shelves,...",
    "image": "https://digiappliances.com/img/products/fridges/DG-RF-TD2HAB126S/close.png",
    "url": "https://digiappliances.com/products/refrigerator-126l",
    "brand": {
      "@type": "Brand",
      "logo": "https://digiappliances.com/img/digi-logo.svg"
    }
  },
  {
    "@context": "http://schema.org",
    "@type": "Product",
    "name": "DIGI Fridge 151 Liters – Fast Cooling, Tempered Glass Shelves,.",
    "image": "https://digiappliances.com/img/products/fridges/DG-RF-TD2HAB222S/close.png",
    "url": "https://digiappliances.com/products/refrigerator-151l",
    "brand": {
      "@type": "Brand",
      "logo": "https://digiappliances.com/img/digi-logo.svg"
    }
  },
  {
    "@context": "http://schema.org",
    "@type": "Product",
    "name": "DIGI Fridge 187 Liters – Fast Cooling, Tempered Glass Shelves,...",
    "image": "https://digiappliances.com/img/products/fridges/DG-RF-TD2HAB228S/close.png",
    "url": "https://digiappliances.com/products/refrigerator-182l",
    "brand": {
      "@type": "Brand",
      "logo": "https://digiappliances.com/img/digi-logo.svg"
    }
  },
  {
    "@context": "http://schema.org",
    "@type": "Product",
    "name": "DIGI Fridge 205 Liters – Fast Cooling, Tempered Glass Shelves,..",
    "image": "https://digiappliances.com/img/products/fridges/DG-RF-TD2HAB322S/close.png",
    "url": "https://digiappliances.com/products/refrigerator-205l",
    "brand": {
      "@type": "Brand",
      "logo": "https://digiappliances.com/img/digi-logo.svg"
    }
  },
  {
    "@context": "http://schema.org",
    "@type": "Product",
    "name": "DIGI Fridge 248 Liters – Fast Cooling, Tempered Glass Shelves,...",
    "image": "https://digiappliances.com/img/products/fridges/DG-RF-TD2HAB412S/close.png",
    "url": "https://digiappliances.com/products/refrigerator-248l",
    "brand": {
      "@type": "Brand",
      "logo": "https://digiappliances.com/img/digi-logo.svg"
    }
  },
  {
    "@context": "http://schema.org",
    "@type": "Product",
    "name": "DIGI Fridge 204 Liters – Bottom Freezer, Fast Cooling, Tempered..",
    "image": "https://digiappliances.com/img/products/fridges/DG-RF-CF2HAB374S/close.png",
    "url": "https://digiappliances.com/products/refrigerator-204l",
    "brand": {
      "@type": "Brand",
      "logo": "https://digiappliances.com/img/digi-logo.svg"
    }
  },
  {
    "@context": "http://schema.org",
    "@type": "Product",
    "name": "DIGI 200L Freezer with Sliding Glass Top, Fast Freeze, LED Ligh...",
    "image": "https://digiappliances.com/img/products/freezers/DG-FZ-CD1HAB315S/closed.png",
    "url": "https://digiappliances.com/products/digi-200l-freezer",
    "brand": {
      "@type": "Brand",
      "logo": "https://digiappliances.com/img/digi-logo.svg"
    }
  },
  {
    "@context": "http://schema.org",
    "@type": "Product",
    "name": "DIGI Freezer 145L With Glass Top, Fast Freeze, LED, Lock & Key,...",
    "image": "https://digiappliances.com/img/products/freezers/DG-FZ-CD1HAB215S/closed.png",
    "url": "https://digiappliances.com/products/digi-145l-freezer",
    "brand": {
      "@type": "Brand",
      "logo": "https://digiappliances.com/img/digi-logo.svg"
    }
  },
  {
    "@context": "http://schema.org",
    "@type": "Product",
    "name": "DIGI Freezer 100L With, Fast Freeze, LED Light, Lock & Key, 5Y..",
    "image": "https://digiappliances.com/img/products/freezers/DG-RF-TD2HAB126S/closed.png",
    "url": "https://digiappliances.com/products/digi-100l-freezer",
    "brand": {
      "@type": "Brand",
      "logo": "https://digiappliances.com/img/digi-logo.svg"
    }
  },
  {
    "@context": "http://schema.org",
    "@type": "Product",
    "name": "DIGI InverterCool Pro 18K – Smart Temp Control, Hidden Display,...",
    "image": "https://digiappliances.com/img/products/ac/1.png",
    "url": "https://digiappliances.com/products/invertercool-pro-18k",
    "brand": {
      "@type": "Brand",
      "logo": "https://digiappliances.com/img/digi-logo.svg"
    }
  },
  {
    "@context": "http://schema.org",
    "@type": "Product",
    "name": "DIGI InverterCool Pro 12K – Smart Temp Control, Hidden Display,...",
    "image": "https://digiappliances.com/img/products/ac/4.png",
    "url": "https://digiappliances.com/products/invertercool-pro-12k",
    "brand": {
      "@type": "Brand",
      "logo": "https://digiappliances.com/img/digi-logo.svg"
    }
  },
  {
    "@context": "http://schema.org",
    "@type": "Product",
    "name": "DIGI Cooker 50x50 Black – 3 Gas + 1 Hot Plate, Electric Oven, T...",
    "image": "https://digiappliances.com/img/products/gas-cooker/DIGI-DG-GC-EMKABF550B-50x50_siyah.png",
    "url": "https://digiappliances.com/products/gas-cooker-50x50-black",
    "brand": {
      "@type": "Brand",
      "logo": "https://digiappliances.com/img/digi-logo.svg"
    }
  },
  {
    "@context": "http://schema.org",
    "@type": "Product",
    "name": "DIGI Cooker 50x50 Steel – 3 Gas + 1 Hot Plate, Electric Oven, T...",
    "image": "https://digiappliances.com/img/products/gas-cooker/DIGI-DG-GC-EMKABF552S-50x50_inox.png",
    "url": "https://digiappliances.com/products/gas-cooker-50x50-steel",
    "brand": {
      "@type": "Brand",
      "logo": "https://digiappliances.com/img/digi-logo.svg"
    }
  },
  {
    "@context": "http://schema.org",
    "@type": "Product",
    "name": "DIGI Cooker 60x60 Black – 3 Gas + 1 Hot Plate, Electric Oven, T...",
    "image": "https://digiappliances.com/img/products/gas-cooker/DIGI-DG-GC-EMKABF651B-60x60_siyah.png",
    "url": "https://digiappliances.com/products/gas-cooker-60x60-black",
    "brand": {
      "@type": "Brand",
      "logo": "https://digiappliances.com/img/digi-logo.svg"
    }
  },
  {
    "@context": "http://schema.org",
    "@type": "Product",
    "name": "DIGI Cooker 60x60 Steel – 3 Gas + 1 Hot Plate, Electric Oven, T...",
    "image": "https://digiappliances.com/img/products/gas-cooker/DIGI-DG-GC-EMKABF650S-60x60_inox.png",
    "url": "https://digiappliances.com/products/gas-cooker-60x60-steel",
    "brand": {
      "@type": "Brand",
      "logo": "https://digiappliances.com/img/digi-logo.svg"
    }
  }
]
</script>
